### ISSUE TITLE
[DE]Availability for german market

### ISSUE THREAD

**Issue by sude22** [fiskaltrust/demo#9]
Hello,
could you give a rough prediction for a working demo for the german market?
Regards

**Comment by sude22** [comment]
Any kind of response would be highly appreciated....

**Comment by holzpfanne** [comment]
Hello
 a beta version is on development at https://github.com/holzpfanne/demo
in the C folder
It is a C code example

**Comment by sude22** [comment]
Hello,
thank you for the info. I try to build my own demo in c#, but I have some problems:
- my Queue is V1.3, build like shown in the FAQs, running as local service
- the "fiskaltrust.interface" Nuget package is only avalible in V1.0 -> doesn't match with V1.3 I guess
- try to test my local service via SOAPUI (using "fiskaltrust_02 WSDL of the Service 1.2.19134.14077.wsdl")->Echo works fine, but Sign fails with error `Der Formatierer hat beim Deserialisieren der Nachricht eine Ausnahme ausgelöst: Fehler beim Deserialisieren von Parameter http://tempuri.org/:data. Die InnerException-Nachricht war "Fehler beim Deserialisieren des Objekts "vom Typ fiskaltrust.ifPOS.v0.ReceiptRequest". Der Wert "‭4919338167972134912‬" kann nicht als Typ "Int64" analysiert werden."`

Is there a chance to get The V1.3 wdsl and nuget package?

**Comment by StefanKert** [comment]
Hi @sude22,

we do have a demo tool for the german market in https://github.com/fiskaltrust/middleware-de-demo-dotnet. You can also check the releases https://github.com/fiskaltrust/middleware-de-demo-dotnet/releases to get the raw binaries. If you have any issues / requests with the german demo please just open an issue there. 

Closing this issue now, but if there are questions open feel free to open it, or if not related to this question create a new one. Thanks :)

**Comment by sude22** [comment]
@StefanKert Thank you for that information, I will have a closer look at it.
